stress-ng: Autospec creation for update from version 0.14.05 to version 0.14.06
Colin Ian King (104):
      stress-wcstr: voidify len2 and strdstlen unused function arguments
      Manual. Update --pathological option documentation, add stressor names
      stress-chdir: clean up pedantic static analysis warning on chdir of null string
      stress-bad-altstack: ensure ret is initialized
      stress-sock: simplyfy the ctrls fetching and free'ing
      stress-sock: remove debug, checked in the wrong version with debug
      stress-sock: only close sfd if it was open
      stress-hash: fix comment, add missing "
      core-nt-store: add ICC compiler support for non-temporal stores
      core-nt-store: restore HAVE_NT_STORE_DOUBLE
      Makefile: icc: enable various cpu specific optimizations
      Makefile: add -fma and -qoverride-limits icc optimization flags
      README.md: add another citation
      core-helper: extend stress_get_memlimits to return totalswap information
      core-helper: add static helper stress_get_meminfo to get memory info
      stress-bad-altstack: for munmap symbol to be fixed up before it is required
      core-helper: move netbsd/freebsd sysctl helpers from core-vmstat.c
      core-smart: remove unnecessary empty smart helper functions for non-SMART builds
      core-helper: partially implement stress_get_meminfo for FreeBSD
      core-helper: remove debug info
      core-helper: implement stress_get_meminfo for NetBSD
      core-helper: fix cut-n-paste error in comment
      core-helper: implement stress_fs_type for FreeBSD
      core-helper: implement stress_fs_type for OpenBSD
      stress-cpu: constify some constant values
      stress-chdir: add some constifications
      stress-chroot: make dev static
      stress-cpu-online: make cpu const
      stress-cyclic: make some variables const
      stress-dentry: constify some variables
      stress-dir: constify gray_code variable
      stress-enosys: reduce scope of pointer h
      stress-epoll: constify variable port
      stress-file-ioctl: constify variables rnd and offset
      stress-hrtimes: make ns_adjust const
      stress-inotify: add parenthesis to clarify logic
      stress-ipsec-mb: constify some variables and minor code cleanup
      stress-loadavg: make variable t_end const
      strress-mlock: constify variable rnd
      stress-msyncmany: make variable pattern const
      stress-opcode: constify a couple of variables
      stress-personality: make variable p const
      stress-pipeherd: make variable dt const
      stress-procfs: make variable sz const
      stress-randlist: fix comment the describes the stressor
      stress-rawdev: make variable offset const
      stress-rmap: make variable offset const
      stress-secretmem: make variable offset const
      stress-shellsort: make variable temp const
      stress-skiplist: make variable v const
      stress-sparsematrix: constify some misc. variables
      stress-splice: Make variabls pipe_size and n const
      stress-str: constify function pointers
      stress-stream: constify some variables
      stress-sync-file: make variable offset const
      stress-sysfs: constify some variables
      stress-itimer: make variables r and ret const
      stress-timerfd: make variable r const
      stress-tree: make variable median const
      stress-tsearch: make pointers const
      stress-vdso: make pointer sym const, add extra parenthesis on time expression
      stress-vecfp: clean up some line white spacing
      stress-vecmath: add missing empty line
      stress-verity: factor out variable rnd
      stress-vm: add some constifications and add some parenthesis
      stress-vm-segv: add missing space before {
      stress-wait: add missing line
      stress-wcstr: constify wide string function pointers
      stress-x86syscall: add register hint to loop counters
      stress-zlib: minor register optimizations
      stress-vm-addr: add a bunch of optimizations to improve throughput
      stress-vm: determine cache line size from cache info or default to 64 bytes
      stress-memthrash: add a translation lookaside buffer thrashing method
      stress-tlb-shootdown: optimize for higher TLB read/write misses
      stress-vm: remove tabs in empty line
      stress-sigsegv: generate SIGSEGV via TSC when TSC access is disabled
      stress-sigsegv: generate SIGSEGV on illegal port read access
      stress-sigsegv: perform illegal vdso calls that can cause SEGVs
      stress-vm-addr: add a bitposn bit flipping powers of 2 address space striding method
      stress-vm-addr: add address bit flip vm-addr method
      stress-memthrash: add a new swapfwdrev 64 bit mempory swapping method
      stress-pagemove: add a stressor to exercise page moving using remap fixed move ops
      stress-vm-addr: remove align attribute from register pointers
      stress-plug: disable for static builds as it requires dlopen
      Add libmd dependency for static builds
      Makefile.config: sort libraries
      stress-regs: fix compilation error with gcc-8 on armel and ppc
      core-arch: add ARC64 arch support macro STRESS_ARCH_ARC64
      stress-sigfpe: disable this stressor for arc64 as feraiseexcept is not implemented
      stress-fp-error: disable stressor for arc64
      stress-fp-error: fix missing continuation \
      stress-sigsegv: compare sigsegv address with expected address
      stress-ng: remove duplicated application name in error message
      stress-sigfpe: force division by zero for x86, disable alarm for m68K
      stress-sigsegv: remove redundant (void *) cast
      stress-sync-file: remove redundant redeclaration of offset
      stress-pagemove: remove redundant assignment to variable page_num
      stress-vm-addr: remove redundant initialization of pointer buf
      README.md: update number of stressors and arches supported
      stress-*: rename CACHE_LINE* macros to STRESS_CACHE_LINE*
      stress-sigsegv: only used expected_addr if SA_SIGINFO is defined
      debian/control: remove Build-Recommends: nonsense
      Makefile: bump version
      Debian: update changelog